export enum ApiRoutes {
  DailyDoneAdd = "daily/done/add",
  DailyFeelingsAdd = "daily/feelings/add",
  DailySubjectsAdd = "daily/subjects/add",
  DailyUnforeseenAdd = "daily/unforeseen/add",
  Daily = "daily",
  DailyFeelingsRemove = "daily/feelings/remove",
  DailySubjectsRemove = "daily/subjects/remove",
  DailyDoneRemove = "daily/done/remove",
  DailyUnforeseenRemove = "daily/unforeseen/remove",
  DailySetDuration = "daily/setDuration",
  TeamCreate = "team/create",
  TeamMembers = "team/members",
  UserTimeline = "user/timeline",
  UserTeams = "user/teams",
  UserInvite = "user/invite",
  UserRequestToJoinTeam = "user/requestToJoinTeam",
  UserCreate = "user/create",
  UserAcceptTeamInvite = "user/acceptTeamInvite",
  UserDeclineTeamInvite = "user/declineTeamInvite",
  Login = "login",
}
